### ISSUE TITLE
static pinpad

### ISSUE THREAD

**Issue by ganges-morekonda** [solomon-okolie/Flutter-PinPad#3]
Numbers in the pinpad are jumbling each time, which creates annoyance for certain use cases / users. Could you please provide a static pinpad so that the numbers states in order all the time.

**Comment by solomon-okolie** [comment]
@ganges-morekonda  I just published version 0.2.0. 

you can use it like
`  var pinPad=PinPad(title: Text('Custom'), scrambleKeys: false);
`
`var pin = await PinPadHelper.requestPin(context: context, pinpad: pinPad);`
